# Generated by Django 4.1.1 on 2022-10-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='loginApp.user')),
                ('visited_by', models.ManyToManyField(related_name='visited_trees', to='loginApp.user')),
            ],
        ),
    ]
