# Generated by Django 2.2.4 on 2022-09-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
