# Generated by Django 2.2.4 on 2022-09-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjasApp', '0003_auto_20220927_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(),
        ),
    ]
