# Generated by Django 4.1.1 on 2022-10-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_regApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
